### PR TITLE
Fix gcc 8.2 warning

### PR DESCRIPTION
**Pull request by outscale-mgo**
Hello,
I've got some warning with npf using gcc 8.2, so I've fix them.

Thanks,
Matthias,

### CODE REVIEW

**Comment by rmind** [comment]
@outscale-mgo: Thanks for the PR. However, it does not seem to be right:
- `copyinstr()` is a function from the NetBSD kernel API. According to its API definition, this routine expects NUL-terminated string; if the string is not terminated or too long, it ought to return `ENAMETOOLONG`. We simply emulate it using `strlcpy()` here (see the point below).
- `strlcpy()` is a function from the BSD API which, by its definition, always NUL-terminates the string (if necessary, by truncation). I do not see why are you deducting a byte from the length (buffer size). It has no real effect; the function does not overrun the buffer.
- Your change to `npf_ifmap_copyname()` passes a larger buffer size that it actually is. This is a bug.

What GCC warnings do you actually get? Alternatively, I can setup the latest GCC 8.x in the weekend and investigate myself.

**Comment by outscale-mgo** [comment]
It seems that gcc 8.2 add a a lot of warning about string, with -Wstringop-truncation.
But as you say, it doesn't work very well with strlcpy, so maybe we should just ignore it.

it seems gcc 8.2 doesn't like casting a function pointer to a function pointer with a different signature, so I cast it into void * first.

Thanks for your time,
Matthias

**Comment by rmind** [comment]
@outscale-mgo: I silenced the warning in `npfkern_pthread_create()`.  However, I do not see any other warnings with GCC 8.2:
```
$ uname -srv
Linux 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19)
$ gcc-8 --version | head -n1
gcc-8 (Debian 8.2.0-21) 8.2.0
$ LIBDIR=/usr/lib DEBUG=1 CC=gcc-8 make clean lib 2> /dev/null | tail -n1
libtool: link: ( cd ".libs" && rm -f "libnpfkern-dbg.la" && ln -s "../libnpfkern-dbg.la" "libnpfkern-dbg.la" )
$ echo $?
0
```
Are you using additional compiler flags? If so, what flags do you use?

**Comment by rmind** [comment]
I assume this is resolved.

**Pull request closed without merging**
