### PR TITLE
add wait_threads to fix a race condition that makes a segfault appears

### PR DESCRIPTION
**Pull request by outscale-gle**
Hello, I found a race condition so i add a function wait_threads on top of npf_destroy and deleted pserialize_perform that is incompatible with wait_threads.

### CODE REVIEW

**Comment by rmind** [comment]
@outscale-gle: This does not seem to be correct. Can you please explain what race do you experience i.e. what exactly is the problem you are trying to solve?

**Comment by outscale-gle** [comment]
Hey thanks for reply, i got a race that make me segfault when a thread is entering `npf_destroy` and another one still alive. This method also fix an infinity loop in `npf_worker_sysfini` during `kthread_join`.

**Comment by rmind** [comment]
@outscale-gle: Problem understood, but it needs a better fix.  I'll try to find time to fix it this week.

**Comment by outscale-gle** [comment]
Ok thanks !

**Comment by rmind** [comment]
This has been fixed by #99.

**Pull request closed without merging**
